### ISSUE TITLE
SnBufferTest.updatesOriginalSensor failed

### ISSUE THREAD

**Issue by pinaf** [teamed/pdd#33]
>
Failed tests: SnBufferTest.updatesOriginalSensor:49 No interactions wanted here: -> at com.sigzig.sensor.SnBufferTest.updatesOriginalSensor(SnBufferTest.java:49) But found this interaction on mock 'Mock for Sensor, hashCode: 2099877756': -> at com.sigzig.sensor.SnBuffer$2.run(SnBuffer.java:89) Actually, above is the only interaction with this mock.

**Comment by pinaf** [comment]
@alex-palevsky it's a valid bug.

**Comment by pinaf** [comment]
oops.. created in wrong project haha!
