### ISSUE TITLE
report failed lines

### ISSUE THREAD

**Issue by yegor256** [teamed/pdd#43]
This report is not informative enough:

```
/Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd/source.rb:45:in `match': invalid byte sequence in UTF-8 (ArgumentError)
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd/source.rb:45:in `block in puzzles'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd/source.rb:44:in `each'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd/source.rb:44:in `each_with_index'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd/source.rb:44:in `puzzles'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd/source.rb:139:in `puzzles'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd.rb:97:in `block (3 levels) in xml'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd.rb:96:in `each'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd.rb:96:in `block (2 levels) in xml'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:391:in `call'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd.rb:95:in `block in xml'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:293:in `initialize'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd.rb:93:in `new'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/lib/pdd.rb:93:in `xml'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/gems/pdd-0.14.2/bin/pdd:90:in `<top (required)>'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/bin/pdd:23:in `load'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/bin/pdd:23:in `<main>'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/yegor/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

Let's report line number.

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.4`
