### ISSUE TITLE
Unhelpful error message "Suspicious TODO in line <num>"

### ISSUE THREAD

**Issue by carlosmiranda** [teamed/pdd#46]
In teamed/xockets-layer#1036, we got the following error message:

```
INFO: "reading src/main/resources/xsl/stats/layout.xsl..."
/var/lib/gems/2.2.0/gems/pdd-0.15.1/lib/pdd/source.rb:144:in `rescue in puzzles': ["in ./src/main/resources/xsl/stats/layout.xsl", #<PDD::Error: Suspicious TODO in line #36>] (PDD::Error)
    from /var/lib/gems/2.2.0/gems/pdd-0.15.1/lib/pdd/source.rb:142:in `puzzles'
    from /var/lib/gems/2.2.0/gems/pdd-0.15.1/lib/pdd.rb:97:in `block (3 levels) in xml'
    from /var/lib/gems/2.2.0/gems/pdd-0.15.1/lib/pdd.rb:96:in `each'
    from /var/lib/gems/2.2.0/gems/pdd-0.15.1/lib/pdd.rb:96:in `block (2 levels) in xml'
    from /var/lib/gems/2.2.0/gems/nokogiri-1.6.6.4/lib/nokogiri/xml/builder.rb:391:in `call'
    from /var/lib/gems/2.2.0/gems/nokogiri-1.6.6.4/lib/nokogiri/xml/builder.rb:391:in `insert'
    from /var/lib/gems/2.2.0/gems/nokogiri-1.6.6.4/lib/nokogiri/xml/builder.rb:375:in `method_missing'
    from /var/lib/gems/2.2.0/gems/pdd-0.15.1/lib/pdd.rb:95:in `block in xml'
    from /var/lib/gems/2.2.0/gems/nokogiri-1.6.6.4/lib/nokogiri/xml/builder.rb:293:in `initialize'
    from /var/lib/gems/2.2.0/gems/pdd-0.15.1/lib/pdd.rb:93:in `new'
    from /var/lib/gems/2.2.0/gems/pdd-0.15.1/lib/pdd.rb:93:in `xml'
    from /var/lib/gems/2.2.0/gems/pdd-0.15.1/bin/pdd:90:in `<top (required)>'
    from /usr/local/bin/pdd:23:in `load'
    from /usr/local/bin/pdd:23:in `<main>'
```

It turns out, it was complaining about a puzzle that looks like the following:

```
                 @todo 1033:30min Below there are two style sections...
```

The problem here is that the format is wrong. It lacks a `#` character before the ticket number and should start with `"@todo #1033:30min`. However, the error message is unhelpful (why is a TODO "suspicious"?). The error should state something useful, similar to:

```
At line 36, formatting is incorrect in TODO starting with "@todo 1033:30min"...
```

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@carlosmiranda I think it's better now: 8bd5a91

**Comment by yegor256** [comment]
@rultor release, tag is `0.15.2`
